/**
 * Reads compiled Hardhat artifacts and generates typed `as const` ABI files
 * under src/abis/. Run after `hardhat compile` as part of the build step.
 *
 * Usage: npx ts-node scripts/generate-abis.ts
 */

import fs from "fs";
import path from "path";

const ARTIFACTS_DIR = path.resolve(__dirname, "../artifacts/contracts");
const OUT_DIR = path.resolve(__dirname, "../src/abis");

const CONTRACTS_TO_EXPORT: Array<{ sol: string; contract: string; exportName: string; typeName: string }> = [
  {
    sol: "EIP7702Implementation.sol",
    contract: "EIP7702Implementation",
    exportName: "eip7702ImplementationAbi",
    typeName: "Eip7702ImplementationAbi",
  },
  {
    sol: "Factory.sol",
    contract: "PlatformAccountFactory",
    exportName: "platformAccountFactoryAbi",
    typeName: "PlatformAccountFactoryAbi",
  },
  {
    sol: "PlatformPaymaster.sol",
    contract: "PlatformPaymaster",
    exportName: "platformPaymasterAbi",
    typeName: "PlatformPaymasterAbi",
  },
];

function toKebab(name: string): string {
  return name
    .replace(/([A-Z]+)([A-Z][a-z])/g, "$1-$2")
    .replace(/([a-z\d])([A-Z])/g, "$1-$2")
    .toLowerCase();
}

function generateFile(exportName: string, typeName: string, abi: object[]): string {
  const abiJson = JSON.stringify(abi, null, 2);
  return `// Auto-generated by scripts/generate-abis.ts — do not edit manually\n\nexport const ${exportName} = ${abiJson} as const;\n\nexport type ${typeName} = typeof ${exportName};\n`;
}

function main() {
  if (fs.existsSync(OUT_DIR)) fs.rmSync(OUT_DIR, { recursive: true });
  fs.mkdirSync(OUT_DIR, { recursive: true });

  const indexLines: string[] = ["// Auto-generated by scripts/generate-abis.ts — do not edit manually\n"];

  for (const { sol, contract, exportName, typeName } of CONTRACTS_TO_EXPORT) {
    const artifactPath = path.join(ARTIFACTS_DIR, sol, `${contract}.json`);

    if (!fs.existsSync(artifactPath)) {
      console.error(`[generate-abis] Missing artifact: ${artifactPath}`);
      console.error("  → Run `npm run build:sol` first.");
      process.exit(1);
    }

    const artifact = JSON.parse(fs.readFileSync(artifactPath, "utf8")) as { abi: object[] };
    const fileName = `${toKebab(contract)}.ts`;
    const outPath = path.join(OUT_DIR, fileName);

    fs.writeFileSync(outPath, generateFile(exportName, typeName, artifact.abi));
    console.log(`[generate-abis] Written ${fileName}`);

    indexLines.push(`export * from "./${fileName.replace(".ts", "")}";`);
  }

  fs.writeFileSync(path.join(OUT_DIR, "index.ts"), indexLines.join("\n") + "\n");
  console.log("[generate-abis] Written index.ts");
}

main();
